version: '3.8'

services:
  bot:
    image: eastwesser/cloud-adtime-bot-aiogram3:latest
    container_name: adtime-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - FUSION_BRAIN_TOKEN=${FUSION_BRAIN_TOKEN}
      - FB_KEY=${FB_KEY}
      - WEBHOOK_MODE=0  # Режим polling
    volumes:
      - bot-data:/app/data
      - bot-logs:/app/logs

volumes:
  bot-data:
  bot-logs: